/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StrokeButton {
        "stroke": string;
    }
    interface UhDash {
    }
    interface UhDashCharacters {
    }
    interface UhDashRadicals {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStrokeButtonElement extends Components.StrokeButton, HTMLStencilElement {
    }
    var HTMLStrokeButtonElement: {
        prototype: HTMLStrokeButtonElement;
        new (): HTMLStrokeButtonElement;
    };
    interface HTMLUhDashElement extends Components.UhDash, HTMLStencilElement {
    }
    var HTMLUhDashElement: {
        prototype: HTMLUhDashElement;
        new (): HTMLUhDashElement;
    };
    interface HTMLUhDashCharactersElement extends Components.UhDashCharacters, HTMLStencilElement {
    }
    var HTMLUhDashCharactersElement: {
        prototype: HTMLUhDashCharactersElement;
        new (): HTMLUhDashCharactersElement;
    };
    interface HTMLUhDashRadicalsElement extends Components.UhDashRadicals, HTMLStencilElement {
    }
    var HTMLUhDashRadicalsElement: {
        prototype: HTMLUhDashRadicalsElement;
        new (): HTMLUhDashRadicalsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stroke-button": HTMLStrokeButtonElement;
        "uh-dash": HTMLUhDashElement;
        "uh-dash-characters": HTMLUhDashCharactersElement;
        "uh-dash-radicals": HTMLUhDashRadicalsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StrokeButton {
        "onStrokeClicked"?: (event: CustomEvent<any>) => void;
        "stroke"?: string;
    }
    interface UhDash {
    }
    interface UhDashCharacters {
    }
    interface UhDashRadicals {
        "onRadSelected"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stroke-button": StrokeButton;
        "uh-dash": UhDash;
        "uh-dash-characters": UhDashCharacters;
        "uh-dash-radicals": UhDashRadicals;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stroke-button": LocalJSX.StrokeButton & JSXBase.HTMLAttributes<HTMLStrokeButtonElement>;
            "uh-dash": LocalJSX.UhDash & JSXBase.HTMLAttributes<HTMLUhDashElement>;
            "uh-dash-characters": LocalJSX.UhDashCharacters & JSXBase.HTMLAttributes<HTMLUhDashCharactersElement>;
            "uh-dash-radicals": LocalJSX.UhDashRadicals & JSXBase.HTMLAttributes<HTMLUhDashRadicalsElement>;
        }
    }
}
